#!/bin/bash
#PBS -S /bin/bash
#PBS -N mbtrack-mpi
#PBS -j eo
#PBS -l nodes=1:ppn=8
#PBS -l walltime=100:00:00
#PBS -l mem=2000mb

# parameters

COMMAND=mbtrack-mpi-debug

INPUT=work/mbtrack_test3_valgrind.conf

NB_TASKS=4


# environment variables

mpivars.sh
export MPIRUN=/usr/local/bin/mpirun
export MPIRUN_OPTS="-f ${PBS_NODEFILE} -r ssh -envall"


# output files

cd ${PBS_O_WORKDIR}

WORK_PATH=work/`date +%Y-%m-%d_%Hh%M`_job${PBS_JOBID}/
mkdir ${WORK_PATH}
cp ${INPUT} ${WORK_PATH}/

STDOUTLOG=${WORK_PATH}/stdout.log
STDERRLOG=${WORK_PATH}/stderr.log

#NB_TASKS=$( cat ${PBS_NODEFILE} | wc -l )

# cluster nodes

#NODES=`sqnodes | sed '1,4d' | awk '/^[a-zA-Z0-9]+ /{print $1}'`
#FREE_NODES=`sqnodes | sed '1,4d' | awk '/free[ \t]*$/{print $1}'`
#sqnodes | sed '1,4d' | awk '/free[ \t]*$/{print $1}' | head -n 10 > mpd.hosts

echo "=== nodes hostname (10 firsts) ===" >> ${STDOUTLOG}
head -n 10 ${PBS_NODEFILE} >> ${STDOUTLOG}
echo >> ${STDOUTLOG}

#
# valgrind binary
#
if [ -e $work/valgrind/bin/valgrind ]
then
  VALGRIND=$work/valgrind/bin/valgrind
else
  VALGRIND=valgrind
fi
$VALGRIND --help >/dev/null 2>&1 || { echo >&2 "Error: valgrind binary not found. For installation instruction go to http://valgrind.org/docs/manual/dist.install.html "; exit 1; }


#
# valgrind options
#
if [ -e /opt/intel/impi/3.2.2.006/etc64/valgrind.supp ]
then
  VALGRIND_SUPP="--suppressions=/opt/intel/impi/3.2.2.006/etc64/valgrind.supp"
fi
if [ -e /usr/share/openmpi/openmpi-valgrind.supp ]
then
  VALGRIND_SUPP="--suppressions=/usr/share/openmpi/openmpi-valgrind.supp"
fi
VALGRIND_MAX="--max-stackframe=208840972 --main-stacksize=128000000"
VALGRIND_OPTS="--tool=callgrind --collect-systime=yes $VALGRIND_SUPP $VALGRIND_MAX"


# 
# execution
#

echo "----------------------------------------"
echo "Running ${COMMAND}"
echo "----------------------------------------"
echo "INPUT:     ${INPUT}"
echo "WORK_PATH: ${WORK_PATH}"
echo "NB_TASKS:  ${NB_TASKS}"
echo "----------------------------------------"

cd ${PBS_O_WORKDIR}
$MPIRUN -np $NB_TASKS $MPIRUN_OPTS $VALGRIND $VALGRIND_OPTS $COMMAND $INPUT $WORK_PATH 2> ${STDERRLOG} >> ${STDOUTLOG}
