; first comment: this example only demonstrate the input syntax
; it is not an actual mbtrack input file (duh)

# other comment: below is a section called "ring"
[ring]

  # below is a parameter called "Lc", which belong to the section "ring"
  Lc = 300.0

  # it is possible to assign a value to a parameter using two different signs (= OR :)
  xyz : 3

# this section demonstrate different data types
[misc]
  
  # integer (can also act as a double)
  fingers = 10

  # double, with a classic notation
  pi = 3.141592653589793238 

  # double, with a scientific notation
  gogol = 1.0e100

  # string
  name = bob

# Not used anymore
# [elements]
#   fire = 1
#   earth = 1
#   water = 0
#   air = 1
