#include <stdbool.h>
#include <stdio.h>
#include <math.h>
#include "fbi.h"
#include "types.h"
#include "bunch.h"
#include "confmpi.h"

#ifndef NAN
# include <bits/nan.h>
#endif

/* Global variables */
extern ring_t ring;
extern tracking_t track;
extern grid_t fbii_grid;

bool fbii_model_init(fbii_model_t * FBIImodel)
{
  /*** Average pressure [mbar] assumed at 300 mA in 3/4 filling ***/
  FBIImodel->Pave      = 2.7e-9;           
  /*** Local pressure in U20                                    ***/
  FBIImodel->Pu20      = 5*FBIImodel->Pave;             
  /*** Partial pressure [Torr] of CO (15%) in U20               ***/   
  FBIImodel->Pm        = 0.15*FBIImodel->Pu20/1.3332;    
  /*** Density [m-3] of CO gas in U20                           ***/
  FBIImodel->dm        = 3.22e22*FBIImodel->Pm;            
  /*** Ionisation cross section [Mb] of CO at 2.75 GeV          ***/ 
  FBIImodel->sigmam    = 1.78;                  
  /*** Length [m] of U20                                        ***/  
  FBIImodel->Lu20      = 1.80;                  
  /*** Length [m] of U20    TODO DUPLICATE !!!                  ***/  
  FBIImodel->Lu20      = 354.0;                 
  /*** Number of CO ions generated by a single electron         ***/ 
  FBIImodel->Ldmsgm    = FBIImodel->Lu20*FBIImodel->dm*FBIImodel->sigmam*1e-22; 

  /*** Mass number of the ion in question (CO)                  ***/
  FBIImodel->Aion      = 28.0;
  /* factF : coupling constant for electron-ion interaction */
  FBIImodel->factF     = E_CHARGE/(FBIImodel->Aion*MP_O_EM*E_MASS);
  
  return true;
}

int fbi_weakstrong_bunch(MPmodel, ionmodel, FBIImodel, ebeam, ionbeam, bCM, kb)
  const bunch_macroparticle_model_t MPmodel;
  ion_model_t * ionmodel;
  const fbii_model_t FBIImodel;
  const e_beam_t ebeam;
  ion_beam_local_t * ionbeam;
  bunch_strong_t * bCM;
  int kb;
{
  int    i, ic, ip, ipp, ip0, msx, msz;
  int    icell;
  double yabs, Dy, xabs, Dx;
  
  double x2di0,y2di0;
  double dQ, factdQ, xi1, xi2, yi1, yi2, uu1[2], uu2[2];
  double Etr[2];
     
  /*** NB: This may be a factor of 2 smaller than that of Ohmi  ***/

  
/*---------------------------------------------------------------------------------------------------*/
/*  The process handled by this module:    (Follow the scheme of Raubenheimer/Zimmermann)            */
/*  At each turn, (by ignoring the chronology among different bunches (i.e. at every instance        */
/*  a bunch arrives at IP (interaction point)), the electric field Ey[ic] created by an              */
/*  eletron bunch is calculated by dividing the bunch into 2*Nslc+1 slices (Nslc=3). The fields      */
/*  Ey[ic] are calculated at the transverse grid points of each cell, which are defined              */
/*  "relative" to centre of mass position of a sliced electron bunch, by taking into account         */
/*  the momentaneous distribution and the betatron oscillation of that turn. The obtained            */
/*  Ey[ic] shall be used subsequently in the actual fast beam-ion interaction of that turn.          */
/*  The address ic is handled by the map that goes together (common to all bunches)                  */
/*                                                                                                   */
/*        ic = mapslice2i[icell][ms+offst]                                                           */
/*         (icell = 0,...,2*Nslc,    ms = -offst,-offst+1,...,-1,0,1,...,offst)                      */ 
/*         (ic = 0,...,(2*Nslc)*Ngrid-1) (Ngrid = 2*offst+1)                                         */
/*         NOTA: (2*Nslc+1)*Ngrid*Ngrid, namely the total number of absolute grid points for         */
/*         an electron bunch, coincides with Nions (= total number of macro ions per bunch.          */
/*                                                                                                   */
/*         NOTA: Nions = (2*Nslc+1)*Ngrid*Ngrid (which in the standard case = (2*3+1)*25*25 = 4375)  */
/*                                                                                                   */
/* The analysed distribution of the electrons on each slice is also used to generate ions.           */
/* Local grid points are defined with respect to the CM position of the electron distribution        */
/* and ions are generated at these points (one macro ion/grid point) following the assumed           */
/* parameters. Reflecting the charge density variation of the electrons, each macro ion              */
/* represent different number of ions. These ions are attracted by Ey[ic] calculated on              */
/* different slices in a self-consistent manner and transformed up to the moment the tail part       */
/* of the electron bunch passes IP. The results are stored as follows:                               */
/*                                                                                                   */
/*        Nri[ip] : Number of ions represented by the macro ion "ip"                                 */
/*        yyi0[ip]: Final amplitude of the macro ion "ip" [m]                                        */
/*        ydi0[ip]: Final slope of the macro ion "ip" [m/s]                                          */
/*          (ip=0,...,Nions-1)   (Nions = (2*Nslc+1)*Ngrid*Ngrid)                                    */
/*---------------------------------------------------------------------------------------------------*/  
    

  const double Nelec     = (ring.Ibunch[kb] * ring.T0 / (MPmodel.Np*E_CHARGE*FKILO));    /*** Number of electrons represented by a macro electron      ***/				     
  const double Convion   = Nelec*FBIImodel.Ldmsgm;                         /*** Number of CO ions generated by a macro electron          ***/

/*
  if(dbg3) {
     if((i = write2outfile(fpo,1," <FBI_bunch> I returning right at the beginning")) < 0);
     return;
  }
*/

/*-------------------------------------------------------------------------------------------*/
/*    In this version, only 2*Nslc+1 (Nslc=3 as default) macro-electrons are used to follow  */
/*    the transverse bunch motion. They represent the centre of mass of the original Np      */
/*    macro-electrons. The total number of these original macro-electrons in cell "icell" is */
/*    represented by npop[icell] (icell=0,...,2*Nslc), and it is already given as the        */
/*    initial condition. Namely, it remains fixed as in this version, the CMs do not move    */
/*    longitudinally.                                                                        */
/*                                                                                           */
/*    xx[icell]: Centre of mass horizontal position of electrons in cell "icell"           */
/*    xp[icell]: Centre of mass horizontal slope (dx/ds) of electrons in cell "icell"      */
/*    zz[icell]: Centre of mass vertical position of electrons in cell "icell"             */
/*    zp[icell]: Centre of mass vertical slope (dz/ds) of electrons in cell "icell"        */
/*    npop[icell]:  Total number of macro-electrons initially counted in cell "icell"        */ 
/*-------------------------------------------------------------------------------------------*/  
  
/*-------------------------------------------------------------------------------------------*/ 
/*    Derivation of electric fields Ex[ic] and Ey[ic] created by the electrons on the        */
/*    absolute grid points:                                                                  */ 
/*    NB: Absolute grids follow the same definition with Ngrid and Ndivs as the local        */
/*-------------------------------------------------------------------------------------------*/ 
  ic = 0;   /*** Used to define mapslice2i[icell][msx+offst][msz+offst] ***/
  
  const int Nslc = ebeam.distrib.Nslc;
  const double deltT = ebeam.distrib.deltT;
  
  const int offst = fbii_grid.offst;
  const double agLOCx = fbii_grid.agLOCx;
  const double agLOCz = fbii_grid.agLOCz;
  const double agABSx = fbii_grid.agABSx;
  const double agABSz = fbii_grid.agABSz;
  
  const double sgm_xx = MPmodel.sgm_xx;
  const double sgm_zz = MPmodel.sgm_zz;
  
  double factBE = FBIImodel.factBE;
  
  //const bunch_weak_distribution_t e_w_distrib = ebeam.w_distrib;
  
  double * Ex = ionbeam->Ex;
  double * Ey = ionbeam->Ey;
  
#ifdef DEBUG_LOG
FILE * edebug = confmpi_log_fopen("efield");
#endif
  
  for(icell=0; icell<2*Nslc+1; icell++) {
     dQ     = Nelec*bCM->npop[icell]*E_CHARGE;                        /*** Electrical charge of the slice icell ***/
     factdQ = dQ/(2*EPSILON0*sqrt(M_PI)*factBE*C_LIGHT*deltT); /*** Factor used in Bassetti-Erskine formula ***/

     for(msx=-offst; msx<offst+1; msx++) {
       /** Electrical field calculation using Bassetti-Erskine formula **/
        xabs = msx*agABSx;
        Dx   = xabs - bCM->xx[icell];
        xi1  = Dx/factBE;
        xi2  = xi1*sgm_zz/sgm_xx;
	
        for(msz=-offst; msz<offst+1; msz++) {
           /*** ( Ex[ic], Ey[ic] ): Electric field at the grid point (msx, msz) in the slice "icell"  ***/       
           yabs = msz*agABSz;              /*** yabs: Indicates a grid point on the absolute axis   ***/
           Dy   = yabs - bCM->zz[icell];
           yi1  = Dy/factBE;
           yi2  = yi1*sgm_xx/sgm_zz;
           if(complex_errorfunc_wofz(xi1, yi1, uu1) < 0)
           {
             fprintf(stderr, "Error: complex_errorfunc_wofz failed\n");
             return -1;
           }
           if(complex_errorfunc_wofz(xi2, yi2, uu2) < 0)
           {
             fprintf(stderr, "Error: complex_errorfunc_wofz failed\n");
             return -1;
           }
#ifdef DEBUG_LOG
if(edebug != NULL)
{
fprintf(edebug, "msx = %8d  ; msz = %8d\n", msx, msz);
fprintf(edebug, "dQ = %14.12g  ;  factdQ = %14.12g\n", dQ, factdQ);
fprintf(edebug, "pi = %14.12g  ;  EPSILON0 = %14.12g\n", M_PI, EPSILON0);
fprintf(edebug, "factBE = %14.12g  ;  C_LIGHT = %14.12g\n", factBE, C_LIGHT);
}
#endif
           Ex[ic] = -factdQ*(uu1[1]-exp(-(Dx*Dx*FMEGA/(2*sgm_xx*sgm_xx)+Dy*Dy*FMEGA/(2*sgm_zz*sgm_zz)))*uu2[1]); 
           Ey[ic] = -factdQ*(uu1[0]-exp(-(Dx*Dx*FMEGA/(2*sgm_xx*sgm_xx)+Dy*Dy*FMEGA/(2*sgm_zz*sgm_zz)))*uu2[0]);
           ic++;
        }  /*** End of loop over msz ***/
	
     }  /*** End of loop over msx ***/
     
  }  /*** End of loop over icell ***/
#ifdef DEBUG_LOG
if(edebug != NULL)
fclose(edebug);
#endif

/*
  if(dbg1) if((i = write2outfile(fpo,1," <FBI_bunch> I have finished preparing Exy[ic] ...")) < 0);
*/
        

/*----------------------------------------------------------------------------------------------*/ 
/*    Generation of ions at local grid points around electron CMs:                              */ 
/*    Procedure:                                                                                */
/*    Start from the head slice (icell=0) of the bunch and build up self-consistently           */
/*    the ions as the bunch traverses the IP, by taking into account the electric force Ey[ic]  */
/*    that attracts the ions created by the precedent slices. The ion distribution, along       */
/*    with their phase space distributions, shall thus represent one at the moment the tail     */
/*    slice passes the IP. We assume here, on the other hand, that the electron motions are     */
/*    not affected by the created ions, on the ground that they are not numerous, in the        */
/*    sense that the head bunch is usually not affected by the ions.                            */
/*----------------------------------------------------------------------------------------------*/   

  ip = 0;   /*** Counts macro-ions across the whole bunch                                     ***/

  for(icell = 0; icell < 2*Nslc+1; icell++) {

     /*** Generation of ions at the position of the electrons                                 ***/
     ip0 = ip;  /*** Benchmark the ion address before working on the new slice                ***/
     for(msx=-offst; msx<offst+1; msx++) {
        for(msz=-offst; msz<offst+1; msz++) {

           /*** Concerns ions to be generated at a transverse point                           ***/
	   /*** (xxCM[icell]+msx*agLOCx, yyCM[icell]+msz*agLOCz), where there are           ***/
           /*** Nofe[icell][msx+offst][msz+offst] macro electrons.                            ***/
           /*** At each grid point, one macro ion shall be created with zero velocity.        ***/
           /*** Each macro ion shall have Nri[ip] that represents the number of ions.         ***/
           /*** (yyi0[ip], ydi0[ip]) shall denote the coordiate and its time derivative       ***/
           /*** of a macro ion "ip".                                                          ***/

           ionbeam->Nri[ip]  = Convion*((double)(ebeam.distrib.Nofe[icell][msx+offst][msz+offst]));
           ionbeam->xxi0[ip] = bCM->xx[icell] + msx*agLOCx;
           ionbeam->xdi0[ip] = 0.0;   /*** Assume that generated ions have zero initial velocity       ***/
           ionbeam->yyi0[ip] = bCM->zz[icell] + msz*agLOCz;
           ionbeam->ydi0[ip] = 0.0;   /*** Assume that generated ions have zero initial velocity       ***/

#ifdef DEBUG_LOG
FILE * fbifp = confmpi_log_fopen("fbi");
if(fbifp != NULL)
{
           fprintf(fbifp,
              " %2d   msx: %2d  msz: %2d   %3d   xCM0: %12.5lf    yCM0: %12.5lf    Nri: %12.5lf    xx: %12.5lf    yy: %12.5lf \n", 
	             icell,msx,msz,ip,bCM->xx[icell]/agABSx,bCM->zz[icell]/agABSz,ionbeam->Nri[ip],ionbeam->xxi0[ip]/agABSx,ionbeam->yyi0[ip]/agABSz);
  fclose(fbifp);
}             
#endif
           ip++; 

        } /*** End of loop over msz ***/
     } /*** End of loop over msx ***/
     
/*     
     if(dbg1) if((i = write2outfile(fpo,1," <FBI_bunch> I have generated ions")) < 0); 
*/
 
/*----------------------------------------------------------------------------------------------*/   
             
     /*** Now, let the ions generated in previous slices be attracted by the electrons      ***/
     /*** in the present slice (cell).                                                      ***/
     /*** Transform their coordinates using linear interpolation for Ey evaluation.         ***/

     for(ipp=0; ipp<ip0; ipp++) {
     			
        if((i = get_linearly_interpolated_Efields(icell, ionbeam->xxi0[ipp], ionbeam->yyi0[ipp], ionbeam, Etr)) < 0);

        x2di0     =  FBIImodel.factF*Etr[0];
        ionbeam->xdi0[ipp] =  ionbeam->xdi0[ipp] + deltT*x2di0;
        ionbeam->xxi0[ipp] =  ionbeam->xxi0[ipp] + deltT*ionbeam->xdi0[ipp]; 
        y2di0     =  FBIImodel.factF*Etr[1];
        ionbeam->ydi0[ipp] =  ionbeam->ydi0[ipp] + deltT*y2di0;
        ionbeam->yyi0[ipp] =  ionbeam->yyi0[ipp] + deltT*ionbeam->ydi0[ipp]; 

     }  /*** End of loop over ipp ***/
     /*pointS:;*/

/*
     if(dbg1) if((i = write2outfile(fpo,1," <FBI_bunch> I have transformed the coordinates of ions")) < 0); 
*/
     
  }   /*** End of loop over icell ***/

  ionmodel->Nions = ip;   /*** Nions: Total number of macro ions per bunch (common to all bunches)       ***/

  /*** NOTA: Nions = (2*Nslc+1)*Ngrid*Ngrid (in the standard case = (2*3+1)*25*25 = 4375)      ***/

/*
  if(dbg1) if((i = write2outfile(fpo,1," <FBI_bunch> I have reached the end of block 4 ...")) < 0); 
*/

/*--------------------------------------------------------------------------------------------------*/
  return 1;
}


int fbi_weakstrong_train(MPmodel, FBIImodel, ebeam, ionlocalbeam, ionbeam, bCM, ib, kb)
  const bunch_macroparticle_model_t MPmodel;
  const fbii_model_t FBIImodel;
  const e_beam_t ebeam;
  ion_beam_local_t * ionlocalbeam;
  ion_beam_t * ionbeam;
  bunch_strong_t * bCM;
  int    ib, kb;
  /*** ib: Index running across active (non empty) bunches (ib=0, ..., Nbunch-1) ***/
  /*** kb: Index running across all bunches (kb = 0, ..., Nharm-1)               ***/
{ 
  int    i, ip;
  int    icell;
  double factRN;

  double x2di0, y2di0, Dtime;
  double x2de0, y2de0, dQ;
  double factjp, factjp0;
  double Etr[2];
  double Nelec;
  
  const double deltT = ebeam.distrib.deltT;
  
  ion_model_t * model = &(ionbeam->model);
/* TODO DEBUG
  int    dbg1  = 0;
  int    dbg2  = 0;
  int    dbg3  = 0;

  if(dbg1) if((i = write2outfile(fpo,1," <FBI_train> I am starting FBI_train")) < 0);

  if(dbg3) {
     if((i = write2outfile(fpo,1," <FBI_train> I returning right at the beginning")) < 0);
     return;
  }
*/
    
  if(ib == 0) {
     /*** Namely, the head bunch in the train: Just update the macro-ion distribution at IP & return ***/
     /*** Macro-ion distribution at IP: { NriFio[],xxFio[],xdFio[],yyFio[],ydFio[] }                 ***/
     model->nFio = 0;   /*** Counts the total number of macro-ions present at IP at a given moment          ***/
     for(ip=0; ip < model->Nions; ip++) {
        ionbeam->NriFio[model->nFio] = ionlocalbeam->Nri[ip];
        ionbeam->yyFio[model->nFio]  = ionlocalbeam->yyi0[ip];
        ionbeam->ydFio[model->nFio]  = ionlocalbeam->ydi0[ip];
        ionbeam->xxFio[model->nFio]  = ionlocalbeam->xxi0[ip];
        ionbeam->xdFio[model->nFio]  = ionlocalbeam->xdi0[ip];
        (model->nFio)++;  
     } 
     model->kbFio = kb;    /*** Bench mark the bunch up to which the macro-ion distribution is treated  ***/
     
     return 0;
  }
  
  factRN = 1e+2;                      /*** WATCH WHAT ONE ASSUMES HERE ***/
  /***factjp = factRN*re/Gamma;***/   /*** Factor to multiply to get a kick from macro-ions     ***/
  
  factjp0 = factRN*4.0*M_PI*EPSILON0*E_RADIUS / ring.Gamma;
  Nelec   = (ring.Ibunch[kb]*ring.T0/(MPmodel.Np*E_CHARGE*FKILO));    /*** Number of electrons represented by a macro electron      ***/				     
 
/*--------------------------------------------------------------------------------------------------*/
  
  /*** Update the coordinates of the macro-ions distribution & add those corresponding      ***/
  /*** to the present bunch to the total distribution:                                      ***/ 

  /*** 1st, transform the total distribution coordinates up to the arrival time of the head ***/
  /*** of kb-bunch at IP (drift transformation):                                            ***/
  

  Dtime = fabs((double)(kb - model->kbFio))*(ring.T0/ring.h);    /*** Time difference (approximate) [sec] between the last & the current bunch ***/
  
  for(ip=0; ip < model->nFio; ip++) {
     ionbeam->xxFio[ip]  =  ionbeam->xxFio[ip] + Dtime * ionbeam->xdFio[ip];
     ionbeam->yyFio[ip]  =  ionbeam->yyFio[ip] + Dtime * ionbeam->ydFio[ip]; 
  } 
    
/*--------------------------------------------------------------------------------------------------*/
  
  /*** 2nd, transform up to the arrival time of the tail of kb-bunch at IP:                       ***/
  /*** Namely, the ions shall now interact with the electric fields of the kb-bunch.              ***/
  /*** Here, we use Ey[ic] prepared in "FBI_bunch" obtained with the Bassetti-Erskine formula.    ***/
  /*** Note that the same Ey[ic] and Ex[ic] as prepared in "FBI_bunch" shall be accessed          ***/
  /*** thanks to the use of "task_ids[ib]" that allows accessing the same "child (bunch)".        ***/
  
  if(FBIImodel.factF == 0)
    fprintf(stderr, "Error: factF = 0\n");
  
  for(icell=0; icell<2*ebeam.distrib.Nslc+1; icell++) {
     dQ = Nelec*bCM->npop[icell]*E_CHARGE;                    /*** Electrical charge of the slice icell ***/
     if(dQ > 0.0) factjp = factjp0/dQ; else factjp = 0.0;
      
     x2de0 = y2de0 = 0.0;  /*** Here we construct the kicks (E-field) felt by a CM-electron simultaneously ***/
     for(ip=0; ip<model->nFio; ip++) {
     	
        if((i = get_linearly_interpolated_Efields(icell, ionbeam->xxFio[ip], ionbeam->yyFio[ip], ionlocalbeam, Etr)) < 0);

        x2di0     =  FBIImodel.factF*Etr[0];
        ionbeam->xdFio[ip] =  ionbeam->xdFio[ip] + deltT*x2di0;
        ionbeam->xxFio[ip] =  ionbeam->xxFio[ip] + deltT*ionbeam->xdFio[ip]; 
        y2di0     =  FBIImodel.factF*Etr[1];
        ionbeam->ydFio[ip] =  ionbeam->ydFio[ip] + deltT*y2di0;
        ionbeam->yyFio[ip] =  ionbeam->yyFio[ip] + deltT*ionbeam->ydFio[ip]; 
        x2de0 =  x2de0 + ionbeam->NriFio[ip]*Etr[0];
        y2de0 =  y2de0 + ionbeam->NriFio[ip]*Etr[1];
	
     }  /*** End of loop over ip (macro-ions) ***/
           
/*--------------------------------------------------------------------------------------------------*/

     /*** Here, we let the macro-electron in icell (i.e. the CM) to interact with macro-ions created by precedent bunches ***/

     x2de0 = factjp*x2de0;
     y2de0 = factjp*y2de0;

     bCM->xp[icell] = bCM->xp[icell] + C_LIGHT*deltT*x2de0;   /***((NB)) The multiplication of deltT here effectively  ***/
     bCM->zp[icell] = bCM->zp[icell] + C_LIGHT*deltT*y2de0;   /***       cancels the dependence of the kick on deltT   ***/
     
#ifdef DEBUG_LOG
/*
     if( dbg2  &&  fabs(zz[icell]) > 0.0) {
        fprintf(fpo, "zz[icell] = %-12.5e  for kb = %3d, icell = %2d", 10000.0*fmil*zz[icell],kb,icell);
     }
*/
#endif

     
  }  /*** End of loop over icell (longitudinal cells) ***/
 
           
/*--------------------------------------------------------------------------------------------------*/

  /*** Add Nions macro-ions generated from the current bunch to the total distribution         ***/
  
  for(ip=0; ip < model->Nions; ip++) {
     ionbeam->NriFio[model->nFio] = ionlocalbeam->Nri[ip];
     ionbeam->yyFio[model->nFio]  = ionlocalbeam->yyi0[ip];
     ionbeam->ydFio[model->nFio]  = ionlocalbeam->ydi0[ip];
     ionbeam->xxFio[model->nFio]  = ionlocalbeam->xxi0[ip];
     ionbeam->xdFio[model->nFio]  = ionlocalbeam->xdi0[ip];
     (model->nFio)++; 
  } 
  
  
  ionbeam->model.kbFio = kb;    /*** Bench mark the bunch up to which the macro-ion distribution is treated  ***/
           
/* TODO debug  
  if(dbg1) if((i = write2outfile(fpo,1," <FBI_train> I have finished FBI_train")) < 0);
*/

  return 1;
}


int get_linearly_interpolated_Efields(icell, xx, yy, ionbeam, Etr)
  int    icell;
  double xx, yy;
  const ion_beam_local_t * ionbeam;
  double Etr[2];
  /*** (xx, yy) represent the coordiates in the absolute axis at which, the E-field shall be calculated ***/
  /*** For the definition of E-fields, see the note RN created in August 2011                           ***/
{ 
  int    k1x, k2x, k1z, k2z;
  int    ic1, ic2, ic3, ic4;
  double Eyy, Eyy5, Eyy6;
  double Exx, Exx5, Exx6;

  const int offst = fbii_grid.offst;  
  const double agABSx = fbii_grid.agABSx;
  const double agABSz = fbii_grid.agABSz;

/*--------------------------------------------------------------------------------------------------*/
/* Date of creation: 12 August 2011                                                                 */
/*--------------------------------------------------------------------------------------------------*/
  
  k1x = (int) (xx/agABSx);
  k1z = (int) (yy/agABSz);
	
  if(yy >= 0) {
     if(k1z < fbii_grid.offst) k2z = k1z+1; else k2z = k1z;
     if(k1z > fbii_grid.offst) k1z = offst;
     if(k2z > fbii_grid.offst) k2z = offst;
	   
     if(xx >= 0) {
        if(k1x < offst) k2x = k1x+1; else k2x = k1x;
        if(k1x > offst) k1x = offst;
        if(k2x > offst) k2x = offst;
	      
        ic1  = ionbeam->mapslice2i[icell][k1x+offst][k1z+offst];
        ic2  = ionbeam->mapslice2i[icell][k2x+offst][k1z+offst];
        ic3  = ionbeam->mapslice2i[icell][k1x+offst][k2z+offst];
        ic4  = ionbeam->mapslice2i[icell][k2x+offst][k2z+offst];
	      
        Eyy5 = ionbeam->Ey[ic1] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic2] - ionbeam->Ey[ic1]);
        Eyy6 = ionbeam->Ey[ic3] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic4] - ionbeam->Ey[ic3]);
        Eyy  = Eyy5             + (yy - k1z*agABSz)/agABSz*(Eyy6 - Eyy5);
        Exx5 = ionbeam->Ex[ic1] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic2] - ionbeam->Ex[ic1]);
        Exx6 = ionbeam->Ex[ic3] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic4] - ionbeam->Ex[ic3]);
        Exx  = Exx5             + (yy - k1z*agABSz)/agABSz*(Exx6 - Exx5);
	      
     } else {
	   
        if(k1x > -offst) k2x = k1x-1; else k2x = k1x;
        if(k1x < -offst) k1x = -offst;
        if(k2x < -offst) k2x = -offst;
	      
        ic1  = ionbeam->mapslice2i[icell][k1x+offst][k1z+offst];
        ic2  = ionbeam->mapslice2i[icell][k2x+offst][k1z+offst];
        ic3  = ionbeam->mapslice2i[icell][k1x+offst][k2z+offst];
        ic4  = ionbeam->mapslice2i[icell][k2x+offst][k2z+offst];
	      
        Eyy5 = ionbeam->Ey[ic1] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic2] - ionbeam->Ey[ic1]);
        Eyy6 = ionbeam->Ey[ic3] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic4] - ionbeam->Ey[ic3]);
        Eyy  = Eyy5    + (yy - k1z*agABSz)/agABSz*(Eyy6 - Eyy5);
        Exx5 = ionbeam->Ex[ic1] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic2] - ionbeam->Ex[ic1]);
        Exx6 = ionbeam->Ex[ic3] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic4] - ionbeam->Ex[ic3]);
        Exx  = Exx5    + (yy - k1z*agABSz)/agABSz*(Exx6 - Exx5);
	      
     }

  } else {

     if(k1z > -offst) k2z = k1z-1; else k2z = k1z;
     if(k1z < -offst) k1z = -offst;
     if(k2z < -offst) k2z = -offst;
	
     if(xx >= 0) {
	if(k1x < offst) k2x = k1x+1; else k2x = k1x;
        if(k1x > offst) k1x = offst;
        if(k2x > offst) k2x = offst;
	   
        ic1  = ionbeam->mapslice2i[icell][k1x+offst][k1z+offst];
        ic2  = ionbeam->mapslice2i[icell][k2x+offst][k1z+offst];
        ic3  = ionbeam->mapslice2i[icell][k1x+offst][k2z+offst];
        ic4  = ionbeam->mapslice2i[icell][k2x+offst][k2z+offst];
	   
        Eyy5 = ionbeam->Ey[ic1] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic2] - ionbeam->Ey[ic1]);
        Eyy6 = ionbeam->Ey[ic3] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic4] - ionbeam->Ey[ic3]);
        Eyy  = Eyy5    - (yy - k1z*agABSz)/agABSz*(Eyy6 - Eyy5);
        Exx5 = ionbeam->Ex[ic1] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic2] - ionbeam->Ex[ic1]);
        Exx6 = ionbeam->Ex[ic3] + (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic4] - ionbeam->Ex[ic3]);
        Exx  = Exx5    - (yy - k1z*agABSz)/agABSz*(Exx6 - Exx5);
	   
     } else  {
	  
        if(k1x > -offst) k2x = k1x-1; else k2x = k1x;
        if(k1x < -offst) k1x = -offst;
        if(k2x < -offst) k2x = -offst;
	   
        ic1  = ionbeam->mapslice2i[icell][k1x+offst][k1z+offst];
        ic2  = ionbeam->mapslice2i[icell][k2x+offst][k1z+offst];
        ic3  = ionbeam->mapslice2i[icell][k1x+offst][k2z+offst];
        ic4  = ionbeam->mapslice2i[icell][k2x+offst][k2z+offst];
	   
        Eyy5 = ionbeam->Ey[ic1] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic2] - ionbeam->Ey[ic1]);
        Eyy6 = ionbeam->Ey[ic3] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ey[ic4] - ionbeam->Ey[ic3]);
        Eyy  = Eyy5    - (yy - k1z*agABSz)/agABSz*(Eyy6 - Eyy5);
        Exx5 = ionbeam->Ex[ic1] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic2] - ionbeam->Ex[ic1]);
        Exx6 = ionbeam->Ex[ic3] - (xx - k1x*agABSx)/agABSx*(ionbeam->Ex[ic4] - ionbeam->Ex[ic3]);
        Exx  = Exx5    - (yy - k1z*agABSz)/agABSz*(Exx6 - Exx5);

     }
  }  

/* TODO there's debug here
  if(dbg1) Eyy = Exx = 0.0;
*/
	
  Etr[0] =  Exx;
  Etr[1] =  Eyy;

#ifdef DEBUG_LOG
/*
FILE * edebug = confmpi_log_fopen("efield");
fprintf(edebug,"after treatment  : %2d  xx: %12.8lf   yy: %12.8lf\n", icell, xx/agABSx, yy/agABSz);
fclose(edebug);
*/
#endif

  return 1;
}


int writeoutCMImotions(output_path, in, ib, ionbeam, ebeam, MPmodel)
  const char * output_path;
  int    in, ib;
  const ion_beam_t * ionbeam;
  const e_beam_t * ebeam;
  const bunch_macroparticle_model_t MPmodel;
{ 
  int ip;
  double xCMI, yCMI, fNTion;
  char filename[FILENAME_MAX];
  char openmode[2];
  FILE * fpoH = NULL;
  FILE * fpoV = NULL;
  char cc;
  
  const char crt = 0x0a;
  const int nFio = ionbeam->model.nFio;
/*
  char dum80A[80], dum140E[140], dum140F[140];
  char cc;
  int dbg0 = 0; 
---------------------------------------------------------------------------------*/
  if(in==0 && ib == 0)
  {
    openmode[0] = 'w';
    openmode[1] = '\0';
  }
  else
  {
    openmode[0] = 'a';
    openmode[1] = '\0';
  }
    
  snprintf(filename, FILENAME_MAX, "%s/CMImotionsH.out", output_path);
  fpoH = fopen(filename, openmode);
  if(fpoH == NULL)
  {
    fprintf(stderr, "Error: cannot open %s !\n", filename);
    return -1;
  }

  snprintf(filename, FILENAME_MAX, "%s/CMImotionsV.out", output_path);
  fpoV = fopen(filename, openmode);
  if(fpoV == NULL)
  {
    fprintf(stderr, "Error: cannot open %s !\n", filename);
    return -1;
  }
  
  xCMI = 0.0;
  yCMI = 0.0;
  fNTion = 0.0;
  for(ip = 0; ip < nFio; ip++) {
     xCMI  =  xCMI + ionbeam->NriFio[ip]*ionbeam->xxFio[ip];
     yCMI  =  yCMI + ionbeam->NriFio[ip]*ionbeam->yyFio[ip];
     fNTion = fNTion + ionbeam->NriFio[ip];
  }

  if(ib == 0)
  {
    fprintf(fpoH, "%3d: ", in);
    fprintf(fpoV, "%3d: ", in);
  }
  
  if(fNTion == 0.0)
  {
    fprintf(fpoH, " %12.8lf", NAN);
    
    fprintf(fpoV, " %12.8lf", NAN);
  }
  else
  {
    xCMI = xCMI/fNTion;
    yCMI = yCMI/fNTion;
    
    fprintf(fpoH, " %12.8lf", FKILO*xCMI/MPmodel.sgm_xx);
    
    fprintf(fpoV, " %12.8lf", FKILO*yCMI/MPmodel.sgm_zz);
  }

  if(ib == ebeam->Nbunch-1) {
     cc = crt;
     putc(cc, fpoH);   
     putc(cc, fpoV);   
  }
  
  fclose(fpoH);
  fclose(fpoV); 
  
  return 1;
}


int writeoutVCMmotionsPM2(output_path, in, bunches, ebeam)
  const char * output_path;
  int in;
  const bunch_strong_t * bunches;
  const e_beam_t * ebeam;
{ 
  int icell;
  unsigned int kb;
  double zCM;
  
  char filename[FILENAME_MAX] = "";
  char openmode[2] = "";
  
  FILE * fpoV = NULL;
  
  const int Nslc = ebeam->distrib.Nslc;
  
  /*
  int dbg0 = 0; 
  */
/*---------------------------------------------------------------------------------*/
/* Introduced to create output files a la PMdata of Aurelien Bence (15 June 2011)  */
/*---------------------------------------------------------------------------------*/

  if(in == 0)
  {
    openmode[0] = 'w';
    openmode[1] = '\0';
  }
  else
  {
    openmode[0] = 'a';
    openmode[1] = '\0';
  }
  
  snprintf(filename, FILENAME_MAX, "%s/CMmotionsV.out", output_path);  
  fpoV = fopen(filename, openmode);
  if(fpoV == NULL)
  {
    fprintf(stderr, "Error: cannot open %s !\n", filename);
    return -1;
  }
  
  /* TODO move CM update out */
  for(kb = 0; kb < ring.Nharm; kb++)
  {
    const bunch_strong_t * bunch = &(bunches[kb]);
    zCM = 0.0;
    if(ebeam->nfFill[kb]) {
       for(icell=0; icell<2*Nslc+1; icell++) zCM = zCM + bunch->zz[icell];
       zCM = zCM/((double) (2*Nslc+1));
    }

     fprintf(fpoV, "%-15.8lf ", 10000.0*FKILO*zCM);  /*** Multiply by 1e4 to be read in by l'appli PMFBT ***/
     /***fprintf(fpoV,"%-12.8lf ", fmil*zCM);      ***/
     /***fprintf(fpoV," %12.8lf", fmil*zCM/sgm_zz);***/
  }
  fprintf(fpoV, "\n");
  fclose(fpoV); 
/*---------------------------------------------------------------------------------------------*/
  return 1;
}
